name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install
        run: |
          pip install Babel
          pip install -e .
      - name: Extract test project
        run: |
          cd testproject/
          pybabel extract -F babelrc -k Label/text -k Resource/catchphrase -k tr -o translations_new.pot .
      - name: Check extracted strings
        run: |
          sed -e '/POT-Creation-Date/d' -e 's/\b20[0-9][0-9]\b/2020/' -e 's/Babel [0-9.]\+/Babel 2.0/' <testproject/translations.pot >expected.pot
          sed -e '/POT-Creation-Date/d' -e 's/\b20[0-9][0-9]\b/2020/' -e 's/Babel [0-9.]\+/Babel 2.0/' <testproject/translations_new.pot >actual.pot
          diff -u expected.pot actual.pot
